"""phase 5: ticket extraction and notification delivery

Revision ID: 1779e429ed0d
Revises: d5b9afd63529
Create Date: 2026-09-21 08:27:32.919195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '1779e429ed0d'
down_revision: Union[str, None] = 'd5b9afd63529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('traveller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTING', 'EXTRACTED', 'CONFIRMED', 'FAILED', 'DISCARDED', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('booking_reference', sa.String(length=120), nullable=True),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.Column('service_number', sa.String(length=60), nullable=True),
    sa.Column('passenger_name', sa.String(length=160), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('depart_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('arrive_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('hotel_name', sa.String(length=160), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=80), nullable=True),
    sa.Column('extraction_error', sa.String(length=500), nullable=True),
    sa.Column('extracted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('confirmed_reference', sa.String(length=120), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['travel_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveller_id'], ['request_travellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_documents_request', 'ticket_documents', ['request_id'], unique=False)
    op.create_index(op.f('ix_ticket_documents_tenant_id'), 'ticket_documents', ['tenant_id'], unique=False)
    op.create_index('ix_ticket_documents_tenant_status', 'ticket_documents', ['tenant_id', 'status'], unique=False)
    op.add_column('notifications', sa.Column('to_address', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('notifications', sa.Column('last_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'last_error')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'attempts')
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'to_address')
    op.drop_index('ix_ticket_documents_tenant_status', table_name='ticket_documents')
    op.drop_index(op.f('ix_ticket_documents_tenant_id'), table_name='ticket_documents')
    op.drop_index('ix_ticket_documents_request', table_name='ticket_documents')
    op.drop_table('ticket_documents')
    # ### end Alembic commands ###
