"""store rendered id proof mask

Revision ID: 638fe0dee15c
Revises: a1f8492e95ed
Create Date: 2026-09-20 23:41:25.778243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '638fe0dee15c'
down_revision: Union[str, None] = 'a1f8492e95ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('id_proofs', sa.Column('number_masked', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('id_proofs', 'number_masked')
    # ### end Alembic commands ###
