"""cab pickup and drop city

Revision ID: 6424d2d65f2e
Revises: 64a83a35ee2c
Create Date: 2026-10-01 19:07:57.519262
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6424d2d65f2e'
down_revision: Union[str, None] = '64a83a35ee2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_requests', sa.Column('pickup_city', sa.String(length=120), nullable=True))
    op.add_column('travel_requests', sa.Column('drop_city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_requests', 'drop_city')
    op.drop_column('travel_requests', 'pickup_city')
    # ### end Alembic commands ###
