"""locations master list and request states

Revision ID: 64a83a35ee2c
Revises: d599c38ad0ba
Create Date: 2026-10-01 18:23:25.020099
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '64a83a35ee2c'
down_revision: Union[str, None] = 'd599c38ad0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_index('ix_locations_tenant_state', 'locations', ['tenant_id', 'state'], unique=False)
    op.create_index('uq_locations_tenant_state_city', 'locations', ['tenant_id', 'state', 'city'], unique=True)
    op.add_column('travel_requests', sa.Column('origin_state', sa.String(length=80), nullable=True))
    op.add_column('travel_requests', sa.Column('destination_state', sa.String(length=80), nullable=True))
    op.add_column('travel_requests', sa.Column('hotel_state', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_requests', 'hotel_state')
    op.drop_column('travel_requests', 'destination_state')
    op.drop_column('travel_requests', 'origin_state')
    op.drop_index('uq_locations_tenant_state_city', table_name='locations')
    op.drop_index('ix_locations_tenant_state', table_name='locations')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
