"""phase 6: notification categories, preferences, dedupe

Revision ID: 68e3b711f417
Revises: 1779e429ed0d
Create Date: 2026-09-21 10:33:33.398325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '68e3b711f417'
down_revision: Union[str, None] = '1779e429ed0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('DECISIONS', 'BOOKINGS', 'ROOM_SHARING', 'REMINDERS', name='notificationcategory', native_enum=False, length=20), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'IN_APP', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'channel', name='uq_preference')
    )
    op.add_column('notifications', sa.Column('category', sa.Enum('DECISIONS', 'BOOKINGS', 'ROOM_SHARING', 'REMINDERS', name='notificationcategory', native_enum=False, length=20), nullable=False))
    op.add_column('notifications', sa.Column('dedupe_key', sa.String(length=120), nullable=True))
    op.create_index('uq_notifications_dedupe', 'notifications', ['user_id', 'channel', 'dedupe_key'], unique=True, mysql_length={'dedupe_key': 120})
    # ### end Alembic commands ###

    # Rows written before this column existed all landed on the DECISIONS
    # default. Put them in the right group, so an opt-out taken today describes
    # the history honestly rather than only what happens next.
    op.execute(
        """
        UPDATE notifications SET category = CASE
            WHEN kind IN ('BOOKING_CONFIRMED', 'REQUEST_BOOKED') THEN 'BOOKINGS'
            WHEN kind = 'COSTAY_REQUESTED' THEN 'ROOM_SHARING'
            WHEN kind IN ('TRAVEL_REMINDER', 'REQUEST_STALE') THEN 'REMINDERS'
            ELSE 'DECISIONS'
        END
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_dedupe', table_name='notifications', mysql_length={'dedupe_key': 120})
    op.drop_column('notifications', 'dedupe_key')
    op.drop_column('notifications', 'category')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
