"""phase 1: users, auth tokens, audit ledger

Revision ID: 6ced969df2ca
Revises: 
Create Date: 2026-09-20 22:43:56.725073
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6ced969df2ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'ADMIN', 'GROUND_STAFF', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('designation', sa.Enum('EXECUTIVE', 'TEAM_LEAD', 'MANAGER', name='designation', native_enum=False, length=20), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender', native_enum=False, length=20), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('base_location', sa.String(length=120), nullable=True),
    sa.Column('theme_preference', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_index('uq_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'SUBMIT', 'APPROVE', 'REJECT', 'CANCEL', 'BOOK', 'UPLOAD', 'EXTRACT', 'NOTIFY', 'OVERRIDE_CONFLICT', 'VIEW_SENSITIVE', name='auditaction', native_enum=False, length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['tenant_id', 'actor_user_id'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('INVITE', 'PASSWORD_RESET', name='tokenpurpose', native_enum=False, length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('used_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_tokens_tenant_id'), 'auth_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_tenant_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_tenant_email', table_name='users')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
