"""phase 7: traveller cost and extracted fare

Revision ID: 994321bd718b
Revises: 68e3b711f417
Create Date: 2026-09-22 17:23:52.208456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '994321bd718b'
down_revision: Union[str, None] = '68e3b711f417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_travellers', sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('request_travellers', sa.Column('cost_currency', sa.String(length=3), nullable=False))
    op.add_column('request_travellers', sa.Column('cost_note', sa.String(length=200), nullable=True))
    op.add_column('request_travellers', sa.Column('cost_entered_by_id', sa.Integer(), nullable=True))
    op.add_column('request_travellers', sa.Column('cost_entered_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.create_foreign_key(None, 'request_travellers', 'users', ['cost_entered_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('ticket_documents', sa.Column('fare_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('ticket_documents', sa.Column('fare_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_documents', 'fare_currency')
    op.drop_column('ticket_documents', 'fare_amount')
    op.drop_constraint(None, 'request_travellers', type_='foreignkey')
    op.drop_column('request_travellers', 'cost_entered_at')
    op.drop_column('request_travellers', 'cost_entered_by_id')
    op.drop_column('request_travellers', 'cost_note')
    op.drop_column('request_travellers', 'cost_currency')
    op.drop_column('request_travellers', 'cost_amount')
    # ### end Alembic commands ###
