"""phase 2: projects, id proofs, exit date

Revision ID: a1f8492e95ed
Revises: 6ced969df2ca
Create Date: 2026-09-20 23:35:52.060112
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'a1f8492e95ed'
down_revision: Union[str, None] = '6ced969df2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_proofs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proof_type', sa.Enum('AADHAAR', 'PAN', 'PASSPORT', 'DRIVING_LICENCE', 'VOTER_ID', 'OTHER', name='idprooftype', native_enum=False, length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('number_encrypted', sa.Text(), nullable=True),
    sa.Column('number_last4', sa.String(length=8), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('purged_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_id_proofs_fingerprint', 'id_proofs', ['tenant_id', 'fingerprint'], unique=False)
    op.create_index(op.f('ix_id_proofs_tenant_id'), 'id_proofs', ['tenant_id'], unique=False)
    op.create_index('ix_id_proofs_user', 'id_proofs', ['tenant_id', 'user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index('ix_projects_tenant_status', 'projects', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_projects_tenant_code', 'projects', ['tenant_id', 'code'], unique=True)
    op.add_column('users', sa.Column('exited_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exited_on')
    op.drop_index('uq_projects_tenant_code', table_name='projects')
    op.drop_index('ix_projects_tenant_status', table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_id_proofs_user', table_name='id_proofs')
    op.drop_index(op.f('ix_id_proofs_tenant_id'), table_name='id_proofs')
    op.drop_index('ix_id_proofs_fingerprint', table_name='id_proofs')
    op.drop_table('id_proofs')
    # ### end Alembic commands ###
