"""phase 3: requests, travellers, revisions, notifications

Revision ID: bc793e8f7a68
Revises: 638fe0dee15c
Create Date: 2026-09-21 06:31:57.681189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'bc793e8f7a68'
down_revision: Union[str, None] = '638fe0dee15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.Enum('LONG_DISTANCE', 'LOCAL_CAB', 'HOTEL', name='requesttype', native_enum=False, length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('mode', sa.Enum('FLIGHT', 'TRAIN', 'BUS', 'CAB', name='travelmode', native_enum=False, length=20), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('start_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('end_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('hotel_city', sa.String(length=120), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_travel_requests_hotel_city', 'travel_requests', ['tenant_id', 'hotel_city'], unique=False)
    op.create_index(op.f('ix_travel_requests_tenant_id'), 'travel_requests', ['tenant_id'], unique=False)
    op.create_index('ix_travel_requests_tenant_project', 'travel_requests', ['tenant_id', 'project_id'], unique=False)
    op.create_index('ix_travel_requests_tenant_requester', 'travel_requests', ['tenant_id', 'requester_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'IN_APP', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'READ', name='notificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('read_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['travel_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('request_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['travel_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'revision_number', name='uq_request_revision')
    )
    op.create_table('request_travellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'BOOKED', 'CANCELLED', name='travellerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('room_sharing', sa.Enum('NOT_OFFERED', 'SHARE_EXISTING', 'SEPARATE_ROOM', 'SEPARATE_HOTEL', name='roomsharingchoice', native_enum=False, length=20), nullable=False),
    sa.Column('share_with_user_id', sa.Integer(), nullable=True),
    sa.Column('share_confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('share_confirmed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['travel_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['share_with_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'user_id', name='uq_request_traveller')
    )
    op.create_index('ix_request_travellers_user_status', 'request_travellers', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_travellers_user_status', table_name='request_travellers')
    op.drop_table('request_travellers')
    op.drop_table('request_revisions')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_travel_requests_tenant_requester', table_name='travel_requests')
    op.drop_index('ix_travel_requests_tenant_project', table_name='travel_requests')
    op.drop_index(op.f('ix_travel_requests_tenant_id'), table_name='travel_requests')
    op.drop_index('ix_travel_requests_hotel_city', table_name='travel_requests')
    op.drop_table('travel_requests')
    # ### end Alembic commands ###
