"""travel reason and other campaign name

Revision ID: d599c38ad0ba
Revises: 994321bd718b
Create Date: 2026-10-01 17:59:44.710216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd599c38ad0ba'
down_revision: Union[str, None] = '994321bd718b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_requests', sa.Column('travel_reason', sa.String(length=500), nullable=True))
    op.add_column('travel_requests', sa.Column('other_project_name', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_requests', 'other_project_name')
    op.drop_column('travel_requests', 'travel_reason')
    # ### end Alembic commands ###
