"""phase 4: traveller decisions

Revision ID: d5b9afd63529
Revises: bc793e8f7a68
Create Date: 2026-09-21 07:20:30.225071
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd5b9afd63529'
down_revision: Union[str, None] = 'bc793e8f7a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_travellers', sa.Column('decided_by_id', sa.Integer(), nullable=True))
    op.add_column('request_travellers', sa.Column('decided_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('request_travellers', sa.Column('decision_reason', sa.String(length=500), nullable=True))
    op.add_column('request_travellers', sa.Column('booking_reference', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'request_travellers', 'users', ['decided_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_travellers', type_='foreignkey')
    op.drop_column('request_travellers', 'booking_reference')
    op.drop_column('request_travellers', 'decision_reason')
    op.drop_column('request_travellers', 'decided_at')
    op.drop_column('request_travellers', 'decided_by_id')
    # ### end Alembic commands ###
